--			ETRADE DATA
--INVOICEDETAILS Fatura Satırları
--ORDERDETAILS Sipariş Satırları
--ORDERS Siparişler
--PAYMENTS Ödemeler
--INVOICES Faturalar
--DISTRICTS Semtler
--ADDRESS Adresler
--USERS Kullanıcılar
--ITEMS Ürünler
--TOWNS İlçeler
--CITIES Şehirler
--COUNTRIES Ülkeler

--2020 yılı ocak ayında verilen siparişleri detaylı şekilde tarihe göre sıralı şekilde getiriniz
SELECT O.DATE_,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
FROM ORDERS O
JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
JOIN ITEMS I ON OD.ITEMID=I.ID
JOIN USERS U ON U.ID=O.USERID
WHERE O.DATE_ BETWEEN '2020-01-01' AND '2020-02-01'
ORDER BY O.DATE_

--Soner Ülgen isimli kullanıcının verdiği şiparişlerin detayını getiren sql sorgusu
select U.namesurname KULLANICI, O.ID SIPARISNO, O.DATE_ SIPARISTARIHI, 
I.ID URUNKODU,  I.ITEMNAME URUNADI, I.BRAND MARKA, I.CATEGORY1 KATEGORİ1, I.CATEGORY2 KATEGORİ2
from users U
JOIN ORDERS O ON O.USERID = U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE U.NAMESURNAME='Soner Ülgen'

--Her şehrin ilçelerini getiren sorgu
select C.CITY, T.TOWN
from CITIES C
JOIN TOWNS T ON T.CITYID=C.ID
ORDER BY CITY,TOWN

-- İstanbulda hangi ilçede ne kadar müşteri var?
SELECT C.CITY SEHİR, T.TOWN İLCE,
	COUNT(U.ID) MUSTERİSAYISI
FROM ADDRESS A
JOIN CITIES C ON C.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN USERS U ON U.ID=A.USERID
WHERE C.CITY='İSTANBUL'
GROUP BY C.CITY,T.TOWN

--2020 YILI MART AYINDA 20-30 YAŞ ARASI MÜŞTERİ SİPARİŞLERİ
SELECT U.NAMESURNAME KULLANICI_ADI,
	DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) YAS, C.CITY SEHIR, O.DATE_ TARIH, O.ID SIPARIS_NO, O.TOTALPRICE TOPTUTAR
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE DATE_ BETWEEN '2020-03-01' AND '2020-04-01' AND DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) BETWEEN 20 AND 30

-- ÇOK ADRESLİ Kullanıcıların hangi şehirde kaç adresi olduğu bilgisini getiriniz.
SELECT 
U.ID KULLANICI_ID, U.NAMESURNAME AD_SOYAD, C.CITY SEHIR, COUNT(DISTINCT A.ADDRESSTEXT)
FROM ADDRESS A
JOIN USERS U ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY U.ID , U.NAMESURNAME , C.CITY
HAVING COUNT(DISTINCT A.ADDRESSTEXT) <> 1

--İstanbulda yılın ilk 3 ayında en çok satış yapılan 10 ürünü
select 
TOP 10 
C.CITY SEHIR, I.ID URUNKODU, I.ITEMNAME URUNADI, I.BRAND MARKA, I.CATEGORY1 KAT1,
I.CATEGORY2 KAT2, I.CATEGORY3 KAT3,
	SUM(OD.AMOUNT) TOPMIKTAR, SUM(O.TOTALPRICE) TOPTUTAR
from ORDERDETAILS OD
JOIN ORDERS O ON OD.ORDERID=O.ID
JOIN ADDRESS A ON O.ADDRESSID= A.ID
JOIN CITIES C ON A.CITYID=C.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE C.CITY='İSTANBUL' AND O.DATE_ BETWEEN '2020-01-01' AND '2020-04-01'
GROUP BY C.CITY, I.ID , I.ITEMNAME, I.BRAND, I.CATEGORY1,
I.CATEGORY2, I.CATEGORY3
ORDER BY SUM(OD.AMOUNT) DESC

--Haftanın günlerine göre ne kadar alışveriş yapıldığı bilgisi
SELECT
	DATENAME(DW, o.DATE_) DAYS,
	ROUND(SUM(O.TOTALPRICE),1) TOPPRICE,
	COUNT(O.ID) TOPCOUNT
FROM 
	ORDERS O
GROUP BY DATENAME(DW, o.DATE_)
ORDER BY DATENAME(DW, o.DATE_)

-- Saat aralığına göre ne kadar alışveriş yapıldığı bilgisi
SELECT
	DATENAME(HOUR, o.DATE_) HOURS,
	ROUND(SUM(O.TOTALPRICE),0) TOPPRICE,
	COUNT(O.ID) TOPCOUNT
FROM 
	ORDERS O
GROUP BY DATENAME(HOUR, o.DATE_)
ORDER BY ROUND(SUM(O.TOTALPRICE),0)

--Her bir sipariş için toplam sevketme süresini getiren sorgu
SELECT O.ID, U.NAMESURNAME,C.CITY,O.DATE_,I.DATE_,DATEDIFF(HOUR, O.DATE_, I.DATE_) 
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID

--Sipariş tarihinin ayı ile fatura tarihinin ayı farklı olan siparişler
SET LANGUAGE TURKİSH
SELECT O.ID, O.DATE_ SIPARISTARIHI, I.DATE_ FATURATARIHI, 
SUM(O.TOTALPRICE) TOPTUTAR, DATENAME(MONTH,O.DATE_) SIPARIS_AYI, DATENAME(MONTH,I.DATE_) FATURA_AYI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY  O.ID, O.DATE_, I.DATE_
HAVING DATENAME(MONTH,O.DATE_) <> DATENAME(MONTH,I.DATE_)

-- Her ay için, sipariş tarihinin ayı ile fatura tarihinin ayı farklı olan sipariş sayılarını getiriniz:
SELECT DATENAME(MONTH,O.DATE_) SIPARIS_AYI, COUNT(DATENAME(MONTH,O.DATE_) )
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_) <> DATENAME(MONTH,I.DATE_)
GROUP BY DATENAME(MONTH,O.DATE_) 

-- Her sehirde ne kadar kadın ne kadar erkek kullanıcı var.
SELECT C.CITY SEHIR, U.GENDER, COUNT(U.ID) KULLANICISAY
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON A.CITYID=C.ID
JOIN USERS U ON O.USERID=U.ID
GROUP BY C.CITY, U.GENDER
ORDER BY C.CITY

-- Ürün kategorilerini alfabetik olarak ana kategori ve en çok satan olarak alt kategori olacak şekilde getiriniz.
SELECT I.CATEGORY1 ANA_KATEGORI, I.CATEGORY2 ALT_KATEGORİ,
	SUM(OD.AMOUNT) TOPLAMSATIS
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY I.CATEGORY1, I.CATEGORY2
ORDER BY CATEGORY1,CATEGORY2


-- Deterjan ve gıda kategorilerindeki ürünlerin bölgelere göre yapılan toplam satışları.
SELECT C.REGION BOLGE,I.CATEGORY1 URUN_KATEGORISI,
SUM(OD.AMOUNT) TOPLAMSATIS
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE I.CATEGORY1 IN ('DETERJAN','GIDA')
GROUP BY C.REGION, I.CATEGORY1
ORDER BY BOLGE