SELECT 
*
FROM 
CUSTOMERS

SELECT
[NAMESURNAME], [GENDER], [BIRTHDATE]
FROM
CUSTOMERS

SELECT
[NAMESURNAME], [GENDER], [BIRTHDATE], [CITY], [TOWN], [TELNR], [TCNO]
FROM
CUSTOMERS

SELECT * FROM CUSTOMERS

TRUNCATE TABLE CUSTOMERS

INSERT INTO CUSTOMERS
(NAMESURNAME,GENDER, BIRTHDATE, CITY, TOWN, TELNR, TCNO)
VALUES
('Ali Cem Duran', 'E', '2001-12-06', 'GAZIANTEP', 'SAHINBEY', '1231231212', '12121212122')

UPDATE CUSTOMERS
SET GSMOPERATOR='Turkcell'

SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())

INSERT INTO CUSTOMERS (NAMESURNAME, GENDER, BIRTHDATE, CITY, TOWN, TELNR, TCNO) VALUES ('Ali Cem Duran', 'E', '2001-12-06', 'GAZIANTEP', 'SAHINBEY', '1231231212', '12121212122')


SELECT * FROM CUSTOMERS
WHERE NAMESURNAME<'D'

SELECT * FROM CUSTOMERS
WHERE NAMESURNAME LIKE '%AN'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '1990-12-12' AND '2012-12-12'

SELECT * FROM CUSTOMERS 
WHERE ID IN (1,14,33)

UPDATE CUSTOMERS
SET GSMOPERATOR ='TURKCELL'
WHERE ID >=1

SELECT * FROM CUSTOMERS
WHERE ID = 1

SELECT * FROM CUSTOMERS
WHERE GENDER = 'E'

SELECT * FROM CUSTOMERS
WHERE GENDER NOT LIKE 'K'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE = '12.06.2001'

SELECT * FROM CUSTOMERS
WHERE ID > 10

SELECT * FROM CUSTOMERS
WHERE ID < 10

SELECT * FROM CUSTOMERS
WHERE ID <=25

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE < '1990.01.01'

SELECT * FROM CUSTOMERS
WHERE ID BETWEEN 10 AND 20

SELECT * FROM CUSTOMERS
WHERE NAMESURNAME BETWEEN 'A' AND 'D'


SELECT * FROM CUSTOMERS
WHERE NAMESURNAME LIKE 'Ali%'

SELECT * FROM CUSTOMERS
WHERE NAMESURNAME  LIKE'% Ali %'

INSERT INTO CUSTOMERS (NAMESURNAME,GENDER,BIRTHDATE,CITY,TOWN,TELNR,TCNO,GSMOPERATOR,AGE)
VALUES ('Ali Can Doron', 'E', '1987.12.14' ,'Izmir', 'Alsancak', '1231231232' ,'23232323233', 'vODAFONE' ,67)

SELECT * FROM CUSTOMERS
WHERE NAMESURNAME LIKE '% Can'

UPDATE CUSTOMERS
SET GENDER='ERKEK' WHERE GENDER='E'

UPDATE CUSTOMERS
SET GENDER='KADIN' WHERE GENDER='K'

UPDATE CUSTOMERS
SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

SELECT * FROM CUSTOMERS
WHERE AGE IN (23,33,43,53,63)

UPDATE CUSTOMERS
SET AGEGROUP='GENC' WHERE AGE BETWEEN 20 AND 40

SELECT * FROM CUSTOMERS
WHERE ID =1



UPDATE CUSTOMERS
SET AGEGROUP='ORTA' WHERE AGE BETWEEN 40 AND 60
UPDATE CUSTOMERS
SET AGEGROUP='YASLI' WHERE AGE >= 60

DELETE FROM CUSTOMERS
WHERE ID = 1

DELETE FROM CUSTOMERS
WHERE NAMESURNAME = 'Ali Can Doron'

delete from customers
where age < 25

select * from customers
where age < 25

delete  from customers
where agegroup='orta'

select * from customers
where agegroup='genc'


select * from customers
where CITY = 'Istanbul' and gender='erkek' or age >40

select * from customers
where CITY='gaziantep' and gender='erkek'

select * from customers
where NAMESURNAME LIKE 'A%' AND AGE BETWEEN 20 AND 50

SELECT * FROM CUSTOMERS
WHERE CITY='ISTANBUL' AND AGE BETWEEN 30 AND 40 OR AGE BETWEEN 50 AND 60

SELECT DISTINCT CITY,TOWN FROM CUSTOMERS
WHERE CITY='GAZİANTEP'


SELECT DISTINCT GENDER FROM CUSTOMERS

SELECT * FROM CUSTOMERS
ORDER BY CITY, NAMESURNAME

SELECT * FROM CUSTOMERS ORDER BY 10,5 DESC

SELECT * FROM CUSTOMERS
ORDER BY BIRTHDATE 

SELECT ID AS MUSTERINO, NAMESURNAME AS ADSOYAD, GENDER AS CINSIYET, CITY AS SEHİR FROM CUSTOMERS AS C

SELECT DISTINCT CITY FROM CUSTOMERS

SELECT DISTINCT TOWN FROM CUSTOMERS
WHERE CITY ='Izmir'

SELECT DISTINCT AGE FROM CUSTOMERS WHERE CITY = 'ANKARA'

SELECT * FROM CUSTOMERS ORDER BY ID

SELECT * FROM CUSTOMERS ORDER BY ID DESC

SELECT * FROM CUSTOMERS ORDER BY NAMESURNAME ASC

SELECT * FROM CUSTOMERS ORDER BY CITY, TOWN

SELECT * FROM CUSTOMERS
WHERE CITY = 'ANKARA'
ORDER BY AGE ASC

SELECT * FROM CUSTOMERS
WHERE CITY = 'ANKARA'
ORDER BY BIRTHDATE

SELECT * FROM CUSTOMERS AS C
ORDER BY TOWN,AGE


SELECT TOP 10 * FROM CUSTOMERS ORDER BY AGE DESC

SELECT TOP 10 *
FROM CUSTOMERS
ORDER BY AGE ASC

SELECT TOP 10 *
FROM CUSTOMERS
WHERE GENDER='KADIN'
ORDER BY AGE ASC

SELECT TOP 5 *
FROM CUSTOMERS
WHERE GENDER = 'ERKEK' AND NAMESURNAME LIKE 'A%'

SELECT TOP 10 PERCENT
* FROM CUSTOMERS
WHERE GENDER = 'ERKEK'
ORDER BY BIRTHDATE

